提出一回目
ryoma-yama/markup_kadai_01 pull request #1
Opened 2020-03-08 15:39 UTC by ryoma-yama

### やったこと
- 見出し
- 区分化
### やってないこと
- なし

2020-03-10 05:46 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-03-10 05:46 UTC, piasoratech commented on markup_kadai_01.html
> +            Email: kaito@quelcode.com
ここは文章ではないので、各行にそれぞれ`p`タグをつけて下さい。

2020-03-10 05:46 UTC, piasoratech commented on markup_kadai_01.html
> +            恵比寿ガーデンプレイス
ここも同じように各行にそれぞれ`p`タグを使用しましょう

2020-03-10 06:44 UTC, ryoma-yama commented
3a72725 該当箇所に`p`タグを追加いたしました。

2020-03-31 16:05 UTC, piasoratech requested changes
コメントしたので確認をお願いします！

2020-03-31 16:05 UTC, piasoratech commented on markup_kadai_01.html
> +        <section>
`section`タグは見出しのタグとセットで使うのでここで`section`タグは使いません。

2020-04-01 01:17 UTC, ryoma-yama commented
0e58f72 にて不適当な`section`を`div`へ置き換えと削除をしました。それと、階層内のカテゴリを揃えて見やすさを上げるために`p`のインデントを調整しました。

2020-04-06 02:37 UTC, piasoratech approved these changes
OKです！

2020-04-16 14:43 UTC, merged